import Sidebar from "@/components/organisms/Sidebar";

export const metadata = {
  title: { default: "Luxury Rent Car", template: "%s" },
  description: "Generated by create next app",
};

function ProfileLayout({ children }) {
  return (
    <div className="flex mx-6 mt-12 mb-36 lg:mb-0 lg:mx-32 lg:mt-14">
      <Sidebar />
      {children}
    </div>
  );
}

export default ProfileLayout;
