import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Rewards",
  description: "Generated by create next app",
};

function Rewards() {
  return (
    <div className="lg:mb-0 lg:mt-10 lg:ml-[25%] w-full select-none">
      <div>
        <h1 className="text-4xl font-bold text-indigo-950">Rewards</h1>
        <p className="mt-2 text-gray-400">
          Collect your rewards by rent our <br /> cars for 10 times.
        </p>
      </div>
      <div className="mt-36 flex flex-col justify-center items-center text-center gap-6">
        <Image
          src={"/assets/svgs/ic-gift.svg"}
          width={100}
          height={100}
          alt="icon_gift"
        />
        <h4 className="text-indigo-950 text-lg">
          You don&apos;t have any rewards :(
        </h4>
      </div>
    </div>
  );
}

export default Rewards;
