"use client";
import Cookies from "js-cookie";
import Image from "next/image";
import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

export default function Settings() {
  return (
    <div className="lg:mb-0 lg:mt-10 lg:ml-[25%] w-full">
      <h1 className="text-4xl font-bold text-indigo-950">Settings</h1>
      <p className="mt-2 text-gray-400">
        Want to costumize <br /> your profile / password?
      </p>

      <div className="mt-10 lg:mt-[70px] grid grid-rows-1 gap-5 lg:grid-cols-3 lg:gap-10">
        <div className="bg-darkGrey rounded-2xl p-6">
          <div className="w-24 h-24">
            <Image
              src={"/assets/svgs/ic-editprofile.svg"}
              width={100}
              height={100}
              alt="icon_editProfile"
            />
          </div>

          <h1 className="mt-5 text-[26px] text-indigo-950 font-bold">
            My Profile
          </h1>
          <p className="mt-2 text-gray-400">Customize your profile</p>
          <Link href={"settings/edit-profile"}>
            <button className="w-full mt-5 bg-zinc-300 text-indigo-950 font-bold py-3 rounded-full">
              Edit Now
            </button>
          </Link>
        </div>

        <div className="bg-darkGrey rounded-2xl p-6">
          <div className="w-24 h-24">
            <Image
              src={"/assets/svgs/ic-lock.svg"}
              width={90}
              height={90}
              alt="icon_lock"
            />
          </div>
          <h1 className="mt-5 text-[26px] text-indigo-950 font-bold">
            My Password
          </h1>
          <p className="mt-2 text-gray-400">Customize your password</p>
          <Link href={"/profile"}>
            <button className="w-full mt-5 bg-zinc-300 text-indigo-950 font-bold py-3 rounded-full">
              Change Now
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}
