import React from "react";

export const metadata = {
  title: "Deposits",
  description: "Generated by create next app",
};

function Deposits() {
  return <div>Deposits</div>;
}

export default Deposits;
